import {
	Bell,
	Boxes,
	Briefcase,
	Calculator,
	ClipboardList,
	Code2,
	Database,
	Factory,
	FileText,
	GitBranch,
	Plug,
	Settings,
	ShieldCheck,
	ShoppingCart,
	TrendingUp,
	UserCog,
	Users,
} from "lucide-react";

export const NAV_ROUTES = {
	default: {
		title: "Home",
		url: "/app/home",
		icon: TrendingUp,
	},
	modules: [
		{
			title: "Finance & Accounting",
			short_form: "F&A",
			url: "/app/finance",
			icon: Calculator,
			sub_modules: [
				{ title: "General Ledger", url: "/gl" },
				{ title: "Accounts Payable", url: "/ap" },
				{ title: "Accounts Receivable", url: "/ar" },
				{ title: "Billing & Invoicing", url: "/billing" },
				{ title: "Tax Management", url: "/tax" },
				{ title: "Expenses", url: "/expenses" },
				{ title: "Budgeting", url: "/budgeting" },
				{ title: "Cash & Treasury", url: "/treasury" },
			],
		},
		{
			title: "Procurement & Purchase Management",
			short_form: "PPM",
			url: "/app/procurement",
			icon: ShoppingCart,
			sub_modules: [
				{ title: "Vendors", url: "/vendors" },
				{ title: "Purchase Requisitions", url: "/requisitions" },
				{ title: "Purchase Orders", url: "/orders" },
				{ title: "RFQ / Quotations", url: "/rfq" },
				{ title: "Approvals", url: "/approvals" },
			],
		},
		{
			title: "Sales & Order Management",
			short_form: "SOM",
			url: "/app/sales",
			icon: TrendingUp,
			sub_modules: [
				{ title: "Quotations", url: "/quotes" },
				{ title: "Orders", url: "/orders" },
				{ title: "Pricing & Discounts", url: "/pricing" },
				{ title: "Contracts", url: "/contracts" },
				{ title: "Order Fulfillment", url: "/fulfillment" },
			],
		},
		{
			title: "Customer Relationship Management",
			short_form: "CRM",
			url: "/app/crm",
			icon: Users,
			sub_modules: [
				{ title: "Leads", url: "/leads" },
				{ title: "Opportunities", url: "/opportunities" },
				{ title: "Customers", url: "/customers" },
				{ title: "Activities", url: "/activities" },
				{ title: "Support Tickets", url: "/tickets" },
			],
		},
		{
			title: "Human Resource Management System",
			short_form: "HRMS",
			url: "/app/hr",
			icon: UserCog,
			sub_modules: [
				{ title: "Employees", url: "/employees" },
				{ title: "Payroll", url: "/payroll" },
				{ title: "Attendance", url: "/attendance" },
				{ title: "Recruitment", url: "/recruitment" },
				{ title: "Performance", url: "/performance" },
			],
		},
		{
			title: "Manufacturing & Operations",
			short_form: "M&O",
			url: "/app/manufacturing",
			icon: Factory,
			sub_modules: [
				{ title: "Production Planning", url: "/planning" },
				{ title: "Work Orders", url: "/work-orders" },
				{ title: "Bill of Materials", url: "/bom" },
				{ title: "Quality Control", url: "/quality" },
				{ title: "Maintenance", url: "/maintenance" },
			],
		},
		{
			title: "Inventory & Warehouse",
			short_form: "INV",
			url: "/app/inventory",
			icon: Boxes,
			sub_modules: [
				{ title: "Stock Overview", url: "/stock" },
				{ title: "Warehouses", url: "/warehouses" },
				{ title: "Transfers", url: "/transfers" },
				{ title: "Batch / Serial Tracking", url: "/tracking" },
				{ title: "Cycle Counts", url: "/counts" },
			],
		},
		{
			title: "Supply Chain",
			short_form: "SCM",
			url: "/app/scm",
			icon: TrendingUp,
			sub_modules: [
				{ title: "Demand Forecasting", url: "/forecasting" },
				{ title: "Supply Planning", url: "/planning" },
				{ title: "Logistics", url: "/logistics" },
				{ title: "Returns", url: "/returns" },
			],
		},
		{
			title: "Project & Service",
			short_form: "P&S",
			url: "/app/projects",
			icon: Briefcase,
			sub_modules: [
				{ title: "Projects", url: "/projects" },
				{ title: "Tasks", url: "/tasks" },
				{ title: "Resources", url: "/resources" },
				{ title: "Field Service", url: "/field-service" },
				{ title: "Service Contracts", url: "/contracts" },
			],
		},
		{
			title: "Analytics & BI",
			short_form: "BI",
			url: "/app/analytics",
			icon: TrendingUp,
			sub_modules: [
				{ title: "Dashboards", url: "/dashboards" },
				{ title: "Reports", url: "/reports" },
				{ title: "Data Explorer", url: "/explorer" },
				{ title: "KPIs", url: "/kpis" },
			],
		},
		{
			title: "Asset Management",
			short_form: "AM",
			url: "/app/assets",
			icon: Boxes,
			sub_modules: [
				{ title: "Asset Register", url: "/register" },
				{ title: "Fixed Assets", url: "/fixed" },
				{ title: "Depreciation", url: "/depreciation" },
				{ title: "Maintenance Schedule", url: "/maintenance" },
				{ title: "Asset Disposal", url: "/disposal" },
			],
		},
	],
	services: [
		{
			title: "IAM",
			short_form: "IAM",
			url: "/app/iam",
			icon: ShieldCheck,
			sub_modules: [
				{ title: "Users", url: "/users" },
				{ title: "Roles", url: "/roles" },
				{ title: "Permissions", url: "/permissions" },
				{ title: "Groups", url: "/groups" },
				{ title: "Identity Providers", url: "/providers" },
			],
		},
		{
			title: "Configuration",
			short_form: "CFG",
			url: "/app/config",
			icon: Settings,
			sub_modules: [
				{ title: "Global Settings", url: "/global" },
				{ title: "Module Settings", url: "/modules" },
				{ title: "Feature Flags", url: "/features" },
			],
		},
		{
			title: "Search",
			short_form: "SRCH",
			url: "/app/search",
			icon: Database,
			sub_modules: [
				{ title: "Global Search", url: "/global" },
				{ title: "Index Management", url: "/index" },
			],
		},
		{
			title: "Audit",
			short_form: "AUD",
			url: "/app/audit",
			icon: ClipboardList,
			sub_modules: [
				{ title: "Audit Logs", url: "/logs" },
				{ title: "Change History", url: "/changes" },
				{ title: "Access Logs", url: "/access" },
				{ title: "Reports", url: "/reports" },
			],
		},
		{
			title: "APIs",
			short_form: "API",
			url: "/app/apis",
			icon: Code2,
			sub_modules: [
				{ title: "API Explorer", url: "/explorer" },
				{ title: "API Keys", url: "/keys" },
				{ title: "Rate Limits", url: "/rate-limits" },
				{ title: "Logs", url: "/logs" },
			],
		},
		{
			title: "Master Data Management",
			short_form: "MDM",
			url: "/app/master-data",
			icon: Database,
			sub_modules: [
				{ title: "Products", url: "/products" },
				{ title: "Customers", url: "/customers" },
				{ title: "Suppliers", url: "/suppliers" },
				{ title: "Locations", url: "/locations" },
				{ title: "Data Quality", url: "/quality" },
			],
		},
		{
			title: "Document & Content Management",
			short_form: "DCM",
			url: "/app/documents",
			icon: FileText,
			sub_modules: [
				{ title: "Documents", url: "/documents" },
				{ title: "Folders", url: "/folders" },
				{ title: "Templates", url: "/templates" },
				{ title: "Approvals", url: "/approvals" },
				{ title: "Archive", url: "/archive" },
			],
		},
		{
			title: "Workflows & Automations",
			short_form: "W&A",
			url: "/app/workflows",
			icon: GitBranch,
			sub_modules: [
				{ title: "Workflows", url: "/workflows" },
				{ title: "Triggers", url: "/triggers" },
				{ title: "Actions", url: "/actions" },
				{ title: "Templates", url: "/templates" },
				{ title: "Logs", url: "/logs" },
			],
		},
	],
	management: [
		{
			title: "Admin",
			short_form: "ADM",
			url: "/app/admin",
			icon: Settings,
			sub_modules: [
				{ title: "Users", url: "/users" },
				{ title: "Roles & Permissions", url: "/roles" },
				{ title: "Organizations", url: "/orgs" },
				{ title: "Subscriptions", url: "/subscriptions" },
			],
		},
		{
			title: "Notification",
			short_form: "NOF",
			url: "/app/notifications",
			icon: Bell,
			sub_modules: [
				{ title: "Templates", url: "/templates" },
				{ title: "Channels", url: "/channels" },
				{ title: "Logs", url: "/logs" },
			],
		},
		{
			title: "Integration",
			short_form: "INT",
			url: "/app/integrations",
			icon: Plug,
			sub_modules: [
				{ title: "Connected Apps", url: "/apps" },
				{ title: "Webhooks", url: "/webhooks" },
			],
		},
	],
	profile: [
		{
			title: "Account",
			short_form: "AM",
			url: "/app/assets",
			icon: Boxes,
			sub_modules: [
				{ title: "Settings", url: "/settings" },
				{ title: "Authentications", url: "/authentication" },
				{ title: "Activity", url: "/activity" },
			],
		},
	],
};
